#include "geometry/mesh.h"
#include "geometry/motion_utils.h"
#include "geometry/patch_builder.h"
#include "geometry/proxy.h"

#include <array>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace {

using Vec3 = std::array<double, 3>;

constexpr double kPi = 3.141592653589793238462643383279502884;

p2cccd::Mesh MakeDebugMesh() {
  p2cccd::Mesh mesh;
  mesh.vertices_ref = {
      {0.0, 0.0, 0.0},
      {1.0, 0.0, 0.0},
      {0.0, 1.0, 0.0},
      {1.0, 1.0, 0.0},
      {2.0, 0.0, 0.0},
      {3.2, 0.0, 0.0},
      {2.0, 0.35, 0.0},
      {3.2, 0.35, 0.0},
  };
  mesh.triangles = {
      {0, 1, 2},
      {1, 3, 2},
      {4, 5, 6},
      {5, 7, 6},
  };
  mesh.patch_ids = {0, 0, 1, 1};
  return mesh;
}

p2cccd::MotionSegment MakeDebugMotion() {
  const double angle = 0.55 * kPi;
  const double half_angle = 0.5 * angle;
  p2cccd::MotionSegment segment;
  segment.t0 = 0.0;
  segment.t1 = 1.0;
  segment.pose_t0.translation = {0.0, 0.0, 0.0};
  segment.pose_t0.rotation_xyzw = {0.0, 0.0, 0.0, 1.0};
  segment.pose_t1.translation = {0.85, 0.45, 0.0};
  segment.pose_t1.rotation_xyzw = {0.0, 0.0, std::sin(half_angle), std::cos(half_angle)};
  return segment;
}

void WriteVec3(std::ostream& out, const Vec3& value) {
  out << '[' << value[0] << ',' << value[1] << ',' << value[2] << ']';
}

bool CheckOk(const p2cccd::Status& status, const char* label) {
  if (status.ok) {
    return true;
  }
  std::cerr << label << " failed: " << status.message << '\n';
  return false;
}

bool WriteTransformedMesh(std::ostream& out,
                          const p2cccd::Mesh& mesh,
                          const p2cccd::PoseSample& pose,
                          const char* layer_name,
                          bool first) {
  for (std::uint32_t triangle_id = 0; triangle_id < mesh.triangles.size(); ++triangle_id) {
    const auto& triangle = mesh.triangles[triangle_id];
    Vec3 v0{};
    Vec3 v1{};
    Vec3 v2{};
    if (!CheckOk(p2cccd::TransformPoint(pose, mesh.vertices_ref[triangle[0]], &v0),
                 "TransformPoint") ||
        !CheckOk(p2cccd::TransformPoint(pose, mesh.vertices_ref[triangle[1]], &v1),
                 "TransformPoint") ||
        !CheckOk(p2cccd::TransformPoint(pose, mesh.vertices_ref[triangle[2]], &v2),
                 "TransformPoint")) {
      return false;
    }

    if (!first) {
      out << ",\n";
    }
    first = false;
    out << "{patch:" << mesh.patch_ids[triangle_id] << ",layer:'" << layer_name << "',verts:[";
    WriteVec3(out, v0);
    out << ',';
    WriteVec3(out, v1);
    out << ',';
    WriteVec3(out, v2);
    out << "]}";
  }
  return true;
}

void WriteHtmlPrefix(std::ostream& out) {
  out << R"P2HTML(<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>P2CCCD Geometry Proxy Debug View</title>
<style>
  body { margin: 0; background: #11150f; color: #e8eadf; font-family: Georgia, 'Times New Roman', serif; }
  #wrap { display: grid; grid-template-columns: 1fr 320px; min-height: 100vh; }
  canvas { width: 100%; height: 100vh; display: block; background:
    radial-gradient(circle at 20% 10%, rgba(120,150,80,0.24), transparent 28%),
    linear-gradient(145deg, #161c12 0%, #0d120d 60%, #17120d 100%); }
  aside { border-left: 1px solid rgba(232,234,223,0.15); padding: 24px; background: rgba(0,0,0,0.26); }
  h1 { font-size: 22px; margin: 0 0 10px; letter-spacing: 0.02em; }
  p { color: #b9c0ad; line-height: 1.45; }
  .legend { margin-top: 22px; display: grid; gap: 12px; }
  .row { display: grid; grid-template-columns: 22px 1fr; gap: 10px; align-items: center; color: #d9dccf; }
  .swatch { width: 22px; height: 14px; border-radius: 3px; border: 1px solid rgba(255,255,255,0.25); }
  .small { margin-top: 28px; font-size: 13px; color: #94a08a; }
</style>
</head>
<body>
<div id="wrap">
<canvas id="view"></canvas>
<aside>
<h1>P2CCCD Proxy Debug View</h1>
<p>This self-contained view shows the current geometry core output: patch mesh, rigid motion samples, endpoint swept AABBs, and capsule proxies across time slabs.</p>
<div class="legend">
  <div class="row"><div class="swatch" style="background:#d79a4a"></div><div>Patch 0 triangles</div></div>
  <div class="row"><div class="swatch" style="background:#70b7a8"></div><div>Patch 1 triangles</div></div>
  <div class="row"><div class="swatch" style="background:rgba(255,255,255,0.12)"></div><div>Swept AABB per slab</div></div>
  <div class="row"><div class="swatch" style="background:#e9e0a6"></div><div>Capsule segment and radius</div></div>
  <div class="row"><div class="swatch" style="background:#ffffff"></div><div>Sampled patch center path</div></div>
</div>
<p class="small">Generated by <code>p2cccd_geometry_proxy_viewer</code>. Projection is XY orthographic; z is ignored in this debug scene.</p>
</aside>
</div>
<script>
const scene = {
)P2HTML";
}

void WriteHtmlSuffix(std::ostream& out) {
  out << R"P2HTML(
};

const canvas = document.getElementById('view');
const ctx = canvas.getContext('2d');
const patchColors = ['#d79a4a', '#70b7a8', '#c88bd8', '#8ba5d8'];

function resize() {
  const dpr = window.devicePixelRatio || 1;
  canvas.width = Math.floor(canvas.clientWidth * dpr);
  canvas.height = Math.floor(canvas.clientHeight * dpr);
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  draw();
}

function eachPoint(callback) {
  for (const tri of scene.triangles) for (const v of tri.verts) callback(v);
  for (const box of scene.aabbs) { callback(box.min); callback(box.max); }
  for (const cap of scene.capsules) { callback(cap.p0); callback(cap.p1); }
  for (const path of scene.paths) for (const p of path.points) callback(p);
}

function bounds() {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  eachPoint((p) => {
    minX = Math.min(minX, p[0]); maxX = Math.max(maxX, p[0]);
    minY = Math.min(minY, p[1]); maxY = Math.max(maxY, p[1]);
  });
  return {minX, minY, maxX, maxY};
}

function makeProjector() {
  const b = bounds();
  const width = canvas.clientWidth;
  const height = canvas.clientHeight;
  const pad = 70;
  const sx = (width - pad * 2) / Math.max(1e-9, b.maxX - b.minX);
  const sy = (height - pad * 2) / Math.max(1e-9, b.maxY - b.minY);
  const scale = Math.min(sx, sy);
  const ox = 0.5 * (width - scale * (b.maxX + b.minX));
  const oy = 0.5 * (height + scale * (b.maxY + b.minY));
  return {
    p: (v) => [ox + v[0] * scale, oy - v[1] * scale],
    r: (value) => Math.max(1.0, value * scale),
  };
}

function drawGrid(project) {
  ctx.save();
  ctx.strokeStyle = 'rgba(255,255,255,0.06)';
  ctx.lineWidth = 1;
  for (let x = -2; x <= 6; x += 0.5) {
    const a = project.p([x, -2, 0]);
    const b = project.p([x, 5, 0]);
    ctx.beginPath(); ctx.moveTo(a[0], a[1]); ctx.lineTo(b[0], b[1]); ctx.stroke();
  }
  for (let y = -2; y <= 5; y += 0.5) {
    const a = project.p([-2, y, 0]);
    const b = project.p([6, y, 0]);
    ctx.beginPath(); ctx.moveTo(a[0], a[1]); ctx.lineTo(b[0], b[1]); ctx.stroke();
  }
  ctx.restore();
}

function polygon(points, fill, stroke, alpha, lineWidth) {
  ctx.save();
  ctx.globalAlpha = alpha;
  ctx.beginPath();
  ctx.moveTo(points[0][0], points[0][1]);
  for (let i = 1; i < points.length; ++i) ctx.lineTo(points[i][0], points[i][1]);
  ctx.closePath();
  if (fill) { ctx.fillStyle = fill; ctx.fill(); }
  if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lineWidth; ctx.stroke(); }
  ctx.restore();
}

function draw() {
  ctx.clearRect(0, 0, canvas.clientWidth, canvas.clientHeight);
  const project = makeProjector();
  drawGrid(project);

  for (const box of scene.aabbs) {
    const min = project.p(box.min);
    const max = project.p(box.max);
    const x = Math.min(min[0], max[0]);
    const y = Math.min(min[1], max[1]);
    const w = Math.abs(max[0] - min[0]);
    const h = Math.abs(max[1] - min[1]);
    ctx.save();
    ctx.fillStyle = `hsla(${box.hue}, 75%, 62%, 0.075)`;
    ctx.strokeStyle = `hsla(${box.hue}, 90%, 72%, 0.36)`;
    ctx.lineWidth = 1.5;
    ctx.fillRect(x, y, w, h);
    ctx.strokeRect(x, y, w, h);
    ctx.restore();
  }

  for (const cap of scene.capsules) {
    const a = project.p(cap.p0);
    const b = project.p(cap.p1);
    ctx.save();
    ctx.strokeStyle = 'rgba(233,224,166,0.28)';
    ctx.lineWidth = project.r(cap.r) * 2.0;
    ctx.lineCap = 'round';
    ctx.beginPath(); ctx.moveTo(a[0], a[1]); ctx.lineTo(b[0], b[1]); ctx.stroke();
    ctx.strokeStyle = 'rgba(233,224,166,0.86)';
    ctx.lineWidth = 2;
    ctx.beginPath(); ctx.moveTo(a[0], a[1]); ctx.lineTo(b[0], b[1]); ctx.stroke();
    ctx.restore();
  }

  for (const path of scene.paths) {
    ctx.save();
    ctx.strokeStyle = path.color;
    ctx.lineWidth = 2;
    ctx.setLineDash([4, 5]);
    ctx.beginPath();
    path.points.forEach((p, i) => {
      const q = project.p(p);
      if (i === 0) ctx.moveTo(q[0], q[1]); else ctx.lineTo(q[0], q[1]);
    });
    ctx.stroke();
    ctx.setLineDash([]);
    for (const p of path.points) {
      const q = project.p(p);
      ctx.beginPath(); ctx.arc(q[0], q[1], 2.4, 0, Math.PI * 2); ctx.fillStyle = path.color; ctx.fill();
    }
    ctx.restore();
  }

  for (const tri of scene.triangles) {
    const pts = tri.verts.map(project.p);
    const color = patchColors[tri.patch % patchColors.length];
    if (tri.layer === 't0') {
      polygon(pts, color, 'rgba(0,0,0,0.45)', 0.72, 1.0);
    } else {
      polygon(pts, null, color, 0.85, 2.2);
    }
  }
}

window.addEventListener('resize', resize);
resize();
</script>
</body>
</html>
)P2HTML";
}

}  // namespace

int main(int argc, char** argv) {
  const std::filesystem::path output_path =
      argc > 1 ? std::filesystem::path(argv[1])
               : std::filesystem::path("src/outputs/geometry_proxy_debug.html");

  p2cccd::Mesh mesh = MakeDebugMesh();
  std::vector<p2cccd::Patch> patches;
  if (!CheckOk(p2cccd::BuildPatchesFromMeshPatchIds(mesh, &patches), "BuildPatchesFromMeshPatchIds")) {
    return 1;
  }

  const p2cccd::MotionSegment motion = MakeDebugMotion();
  std::vector<p2cccd::TimeSlab> slabs;
  if (!CheckOk(p2cccd::GenerateTimeSlabsForMotionSegment(motion, 4, &slabs),
               "GenerateTimeSlabsForMotionSegment")) {
    return 1;
  }

  p2cccd::PoseSample pose_t0;
  p2cccd::PoseSample pose_t1;
  if (!CheckOk(p2cccd::InterpolateRigidMotion(motion, motion.t0, &pose_t0),
               "InterpolateRigidMotion(t0)") ||
      !CheckOk(p2cccd::InterpolateRigidMotion(motion, motion.t1, &pose_t1),
               "InterpolateRigidMotion(t1)")) {
    return 1;
  }

  std::filesystem::create_directories(output_path.parent_path());
  std::ofstream out(output_path);
  if (!out) {
    std::cerr << "failed to open output file: " << output_path.string() << '\n';
    return 1;
  }

  WriteHtmlPrefix(out);

  out << "triangles:[\n";
  if (!WriteTransformedMesh(out, mesh, pose_t0, "t0", true)) {
    return 1;
  }
  if (!WriteTransformedMesh(out, mesh, pose_t1, "t1", false)) {
    return 1;
  }
  out << "\n],\n";

  out << "aabbs:[\n";
  bool first = true;
  const double eps_proxy = 0.04;
  for (const p2cccd::Patch& patch : patches) {
    for (const p2cccd::TimeSlab& slab : slabs) {
      p2cccd::EndpointSweptAabbProxy proxy;
      if (!CheckOk(p2cccd::BuildEndpointSweptAabbProxy(patch, motion, slab, eps_proxy, &proxy),
                   "BuildEndpointSweptAabbProxy")) {
        return 1;
      }
      if (!first) {
        out << ",\n";
      }
      first = false;
      out << "{patch:" << patch.patch_id << ",slab:" << slab.slab_id << ",hue:"
          << (38 + 105 * patch.patch_id + 15 * slab.slab_id) << ",min:";
      WriteVec3(out, proxy.bounds.min);
      out << ",max:";
      WriteVec3(out, proxy.bounds.max);
      out << '}';
    }
  }
  out << "\n],\n";

  out << "capsules:[\n";
  first = true;
  for (const p2cccd::Patch& patch : patches) {
    for (const p2cccd::TimeSlab& slab : slabs) {
      p2cccd::CapsuleProxy proxy;
      if (!CheckOk(p2cccd::BuildCapsuleProxy(patch, motion, slab, eps_proxy, &proxy),
                   "BuildCapsuleProxy")) {
        return 1;
      }
      if (!first) {
        out << ",\n";
      }
      first = false;
      out << "{patch:" << patch.patch_id << ",slab:" << slab.slab_id << ",p0:";
      WriteVec3(out, proxy.endpoint0);
      out << ",p1:";
      WriteVec3(out, proxy.endpoint1);
      out << ",r:" << proxy.radius << '}';
    }
  }
  out << "\n],\n";

  out << "paths:[\n";
  first = true;
  for (const p2cccd::Patch& patch : patches) {
    if (!first) {
      out << ",\n";
    }
    first = false;
    out << "{patch:" << patch.patch_id << ",color:'"
        << (patch.patch_id == 0 ? "#ffffff" : "#bbfff1") << "',points:[";
    for (std::uint32_t i = 0; i <= 24; ++i) {
      const double t = static_cast<double>(i) / 24.0;
      p2cccd::PoseSample pose;
      Vec3 center{};
      if (!CheckOk(p2cccd::InterpolateRigidMotion(motion, t, &pose), "InterpolateRigidMotion") ||
          !CheckOk(p2cccd::TransformPoint(pose, patch.local_center, &center), "TransformPoint")) {
        return 1;
      }
      if (i != 0) {
        out << ',';
      }
      WriteVec3(out, center);
    }
    out << "]}";
  }
  out << "\n]\n";

  WriteHtmlSuffix(out);
  std::cout << "wrote " << std::filesystem::absolute(output_path).string() << '\n';
  return 0;
}
